/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yjn_text_JniClient */

#ifndef _Included_com_yjn_text_JniClient
#define _Included_com_yjn_text_JniClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_yjn_text_JniClient
 * Method:    getFasetBlurPix
 * Signature: ([IIII)[I
 */
JNIEXPORT jintArray JNICALL Java_com_yjn_text_JniClient_getFasetBlurPix
  (JNIEnv *, jclass, jintArray, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
